### ISSUE TITLE
nathan is an issue

### ISSUE THREAD

**Issue by toonjoey** [averagedeveloper2k/TTPAWorkingSRC#3]
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
Preloading suits...
Preloading Toon heads...
Preloading avatars...
Traceback (most recent call last):
  File "toontown\toon\ToonHead.py", line 64, in preload
    PreloadHeads['phase_3' + fileRoot + '1000'] = loader.loadModel('phase_3' + fileRoot + '1000')
  File "toontown\toonbase\ToontownLoader.py", line 72, in loadModel
    ret = nLoader.Loader.loadModel(self, *args, **kw)
  File "C:\Panda3D-1.10.0\direct\showbase\Loader.py", line 170, in loadModel
    raise IOError, message
IOError: Could not load model file(s): ['phase_3/models/char/deer-heads-1000']
direct.gui.DirectGuiBase:1035, direct.gui.DirectFrame:51, toontown.toontowngui.ToontownLoadingScreen:30, toontown.toonbase.ToontownLoader:18, NameError: global name 'base' is not defined
Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\TTPAWorkingSRC-master\toontown\toonbase\ClientStart.py", line 213, in <module>
    base.run()
  File "otp\otpbase\OTPBase.py", line 250, in run
    self.destroy()
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 514, in destroy
    self.loader.destroy()
  File "toontown\toonbase\ToontownLoader.py", line 18, in destroy
    self.loadingScreen.destroy()
  File "toontown\toontowngui\ToontownLoadingScreen.py", line 30, in destroy
    self.tip.destroy()
  File "C:\Panda3D-1.10.0\direct\gui\DirectFrame.py", line 51, in destroy
    DirectGuiWidget.destroy(self)
  File "C:\Panda3D-1.10.0\direct\gui\DirectGuiBase.py", line 1035, in destroy
    if hasattr(base, 'guiItems'):
NameError: global name 'base' is not defined
Sentry is attempting to send 2 pending error messages
Waiting up to 10 seconds
Press Ctrl-Break to quit

**Comment by toonjoey** [comment]
also no crankys allowed
